Documentation verification and updates
coreos/quay-docs pull request #68
Opened 2017-04-26 21:37 UTC by josephschorr

2017-04-26 21:41 UTC, jakedt requested changes

2017-04-26 21:41 UTC, jakedt commented on guides/notifications.md
>  #### <img class="method-icon" src="https://quay.io/static/img/favicon.ico" style="width: 22px; height: 22px;">Quay.io Notification
This is the old logo....

2017-04-26 21:44 UTC, josephschorr commented on guides/notifications.md
>  #### <img class="method-icon" src="https://quay.io/static/img/favicon.ico" style="width: 22px; height: 22px;">Quay.io Notification
Fixed

2017-04-27 01:02 UTC, jakedt approved these changes

2017-04-27 01:38 UTC, merged